# Use an official Python runtime as a parent image
FROM python:3.8

# Set environment variables
ENV PYTHONUNBUFFERED 1


# Set the working directory in the container
WORKDIR /code

# Copy the requirements file into the container at /code/
COPY requirements.txt /code/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code into the container at /code/
COPY . /code/

# Expose the port on which your Django app will run
EXPOSE 8000

# Run the Django development server when the container launches
CMD ["python", "SSH/manage.py", "runserver","0.0.0.0:8000"]




